### PR TITLE
Address 714 and 705 

### PR DESCRIPTION
**Pull request by FrancescoVassalli**

### CODE REVIEW

**Comment by FrancescoVassalli** [comment]
Hold up I messed up the base branch so the merge is wrong. Will fix

**Comment by FrancescoVassalli** [comment]
Actually I don't think this is my fault. It looks like the 11-15 release does not have all the changes from the 11-1 release. It probably should

**Comment by surapuramakhil** [comment]
@FrancescoVassalli it happens if new PR merges happen after creating 11-15 release. we can just create a PR pushing any new changes of 11-1 to 11-15

**Comment by FrancescoVassalli** [comment]
> @FrancescoVassalli it happens if new PR merges happen after creating 11-15 release. we can just create a PR pushing any new changes of 11-1 to 11-15

Right. I'll make that now. We can discuss further there

**Comment by FrancescoVassalli** [comment]
Nevermind. I need collaborator permission to do that

**Review by surapuramakhil — APPROVED** [review]

**Pull request merged**
